export const LOG_IN = "LOG_IN";
export const ADD_PATIENT = "ADD_PATIENT";
export const SHOW_PATIENTS = "SHOW_PATIENT";
export const PATIENT_DELETE="PATIENT_DELETE";

export const GET_PATIENT_BY_ID="GET_PATIENT_BY_ID";

export const UPDATE_PATIENT="UPDATE_PATIENT";
export const IS_POP_UP_OPEN="IS_POP_UP_OPEN";

export const IS_POP_UP_CLOSE="IS_POP_UP_CLOSE";

export const PAGEDATA = "PAGEDATA";

export const LODERSTATESCHANGE = "LODERSTATESCHANGE";

export const INCURRUNTPAGE = "INCURRUNTPAGE";

export const DICURRUNTPAGE="DICURRUNTPAGE";
